set-option -g status-position top
set -g default-command fish
set-option -g prefix C-q
unbind-key C-q
bind-key C-q send-prefix
set -g mouse on
set-option -g default-terminal 'tmux-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind-key v split-window -h
bind-key h split-window -v
bind-key u split-window "aerospace focus --window-id $(aerospace list-windows --all | fzf --height 40% --color 'border:#ffa07a,info:#ffff00' --border | cut -d'|' -f1 | tr -d '[:blank:]')"
bind -n S-Left previous-window
bind -n S-Right next-window
set -g renumber-windows "on"
set -g @continuum-restore "on"
set -g @resurrect-strategy-nvim 'session'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"
# set -g @catppuccin_date_time_text "%d.%m. %H:%M"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session} "
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
# set -ag status-right "#S #[fg=#{@thm_fg},bg=#{@thm_mantle}] #(tmux-mem-cpu-load --interval 2 | cut -d ' ' -f1 )#[default]"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -ag status-right "#{E:@catppuccin_status_date_time}"
# set -agF status-right "#{E:@catppuccin_status_battery}"
# run-shell ${pkgs.tmuxPlugins.cpu}/share/tmux-plugins/cpu/cpu.tmux
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi v send -X selection-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
